# Generated by Django 6.0.5 on 2026-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('business', 'Business'), ('staff', 'Staff')], default='business', max_length=20),
        ),
    ]
